### ISSUE TITLE
Feature request: delete last input

### ISSUE THREAD

**Issue by morganm362** [tgilbert11/life-data#21] opened 2015-11-28 20:29 UTC
Instead of deleting the most recent time event, deleting the most recent edit would be preferred. :)

**Comment by tgilbert11** [comment] 2015-11-28 20:31
there is a new feature on the list that would enable deleting directly from the list view, and you can delete any of the items you want.  I'm adding this bug as a duplicate of that feature request

**Comment by tgilbert11** [comment] 2015-11-28 20:35
duplicate of #8

**Closed as completed by tgilbert11** 2015-11-28 20:35 UTC
Labels: duplicate
